openapi: "3.0.0"
info:
  version: 1.0.0
  title: Nhost Auth
  description: Service to Authenticate
  termsOfService: http://swagger.io/terms/
  contact:
    name: Nhost's Support
    email: support@nhost.io
    url: https://nhost.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /signup/email-password:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpEmailPasswordSchema'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionPayload'
          description: >-
            Successfully registered. Null session means email verification is
            pending
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: >-
            Signup mechanism is disabled
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: >-
            User with given email already exists

      summary: Signup with email and password
      tags:
        - signup
        - email-and-password

components:
  schemas:
    ErrorResponse:
      type: object
      additionalProperties: false
      properties:
        status:
          description: HTTP status error code
          type: integer
        message:
          description: Human friendly error message
          type: string
        error:
          description: Error code that identifies the application error
          type: string
          enum:
            - internal-server-error
            - invalid-request
            - signup-disabled
            - email-already-in-use
            - password-too-short
            - password-in-hibp-database
            - role-not-allowed
            - locale-not-allowed
            - default-role-must-be-in-allowed-roles
            - redirecTo-not-allowed
      required:
        - status
        - message
        - error

    SessionPayload:
      type: object
      additionalProperties: false
      properties:
        session:
          $ref: "#/components/schemas/Session"

    Session:
      type: object
      additionalProperties: false
      properties:
        accessToken:
          type: string
        accessTokenExpiresIn:
          type: integer
          format: int64
        refreshToken:
          description: Refresh token during authentication or when refreshing the JWT
          example: 2c35b6f3-c4b9-48e3-978a-d4d0f1d42e24
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
        user:
          $ref: '#/components/schemas/User'
      required:
        - accessToken
        - accessTokenExpiresIn
        - refreshToken

    User:
      type: object
      additionalProperties: false
      properties:
        avatarUrl:
          type: string
        createdAt:
          format: date-time
          type: string
        defaultRole:
          example: user
          type: string
        displayName:
          example: John Smith
          type: string
        email:
          description: A valid email
          example: john.smith@nhost.io
          format: email
          type: string
        emailVerified:
          type: boolean
        id:
          description: Id of the user
          example: 2c35b6f3-c4b9-48e3-978a-d4d0f1d42e24
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
        isAnonymous:
          type: boolean
        locale:
          description: A two-characters locale
          example: en
          maxLength: 2
          minLength: 2
          type: string
        metadata:
          type: object
          additionalProperties: true
          example:
            firstName: John
            lastName: Smith
          properties: {}
        phoneNumber:
          type: string
        phoneNumberVerified:
          type: boolean
        roles:
          example:
            - me
            - user
          type: array
          items:
            type: string
      required:
        - createdAt
        - displayName
        - avatarUrl
        - locale
        - email
        - isAnonymous
        - defaultRole
        - metadata
        - activeMfaType
        - emailVerified
        - phoneNumber
        - phoneNumberVerified
        - roles

    SignUpEmailPasswordSchema:
      type: object
      additionalProperties: false
      properties:
        email:
          description: A valid email
          example: john.smith@nhost.io
          format: email
          type: string
        password:
          description: A password of minimum 3 characters
          example: Str0ngPassw#ord-94|%
          minLength: 3
          type: string
        options:
          $ref: "#/components/schemas/SignUpOptions"
      required:
        - email
        - password

    SignUpOptions:
      type: object
      additionalProperties: false
      properties:
        allowedRoles:
          example:
            - me
            - user
          type: array
          items:
            type: string
        defaultRole:
          example: user
          type: string
        displayName:
          example: John Smith
          type: string
        locale:
          description: A two-characters locale
          example: en
          maxLength: 2
          minLength: 2
          type: string
        metadata:
          type: object
          additionalProperties: true
          example:
            firstName: John
            lastName: Smith
          properties: {}
        redirectTo:
          example: https://my-app.com/catch-redirection
          type: string
