// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get public keys for JWT verification in JWK Set format
	// (GET /.well-known/jwks.json)
	GetWellKnownJwksJson(c *gin.Context)
	// Health check
	// (GET /healthz)
	GetHealthz(c *gin.Context)
	// Health check
	// (HEAD /healthz)
	HeadHealthz(c *gin.Context)
	// Link a user account with the provider's account using an id token
	// (POST /link/idtoken)
	PostLinkIdtoken(c *gin.Context)
	// Generate TOTP secret for MFA setup
	// (GET /mfa/totp/generate)
	GetMfaTotpGenerate(c *gin.Context)
	// Create a Personal Access Token (PAT)
	// (POST /pat)
	PostPat(c *gin.Context)
	// Sign in anonymously
	// (POST /signin/anonymous)
	PostSigninAnonymous(c *gin.Context)
	// Sign in with email and password
	// (POST /signin/email-password)
	PostSigninEmailPassword(c *gin.Context)
	// Sign in with in an id token
	// (POST /signin/idtoken)
	PostSigninIdtoken(c *gin.Context)
	// Verify TOTP and return a session if validation is successful
	// (POST /signin/mfa/totp)
	PostSigninMfaTotp(c *gin.Context)
	// Sign in with a one time password sent to user's email. If the user doesn't exist, it will be created. The options object is optional and can be used to configure the user's when signing up a new user. It is ignored if the user already exists.
	// (POST /signin/otp/email)
	PostSigninOtpEmail(c *gin.Context)
	// Verify OTP and return a session if validation is successful
	// (POST /signin/otp/email/verify)
	PostSigninOtpEmailVerify(c *gin.Context)
	// Sign in with magic link sent to user's email. If the user doesn't exist, it will be created. The options object is optional and can be used to configure the user's when signing up a new user. It is ignored if the user already exists.
	// (POST /signin/passwordless/email)
	PostSigninPasswordlessEmail(c *gin.Context)
	// Sign in with Personal Access Token (PAT)
	// (POST /signin/pat)
	PostSigninPat(c *gin.Context)
	// Sign in with an oauth2 provider
	// (GET /signin/provider/{provider})
	GetSigninProviderProvider(c *gin.Context, provider GetSigninProviderProviderParamsProvider, params GetSigninProviderProviderParams)
	// Callback for oauth2 provider
	// (GET /signin/provider/{provider}/callback)
	GetSigninProviderProviderCallback(c *gin.Context, provider GetSigninProviderProviderCallbackParamsProvider, params GetSigninProviderProviderCallbackParams)
	// Signin with webauthn
	// (POST /signin/webauthn)
	PostSigninWebauthn(c *gin.Context)
	// Verify webauthn signin
	// (POST /signin/webauthn/verify)
	PostSigninWebauthnVerify(c *gin.Context)
	// Signup with email and password
	// (POST /signup/email-password)
	PostSignupEmailPassword(c *gin.Context)
	// Signup with webauthn
	// (POST /signup/webauthn)
	PostSignupWebauthn(c *gin.Context)
	// Verify webauthn signup
	// (POST /signup/webauthn/verify)
	PostSignupWebauthnVerify(c *gin.Context)
	// Refresh the JWT access token
	// (POST /token)
	PostToken(c *gin.Context)
	// Deanonymize an anonymous user in adding missing email or email+password, depending on the chosen authentication method. Will send a confirmation email if the server is configured to do so
	// (POST /user/deanonymize)
	PostUserDeanonymize(c *gin.Context)
	// Change user email
	// (POST /user/email/change)
	PostUserEmailChange(c *gin.Context)
	// Send email verification email
	// (POST /user/email/send-verification-email)
	PostUserEmailSendVerificationEmail(c *gin.Context)
	// Activate/deactivate Multi-factor authentication
	// (POST /user/mfa)
	PostUserMfa(c *gin.Context)
	// Change user password. The user must be authenticated or provide a ticket
	// (POST /user/password)
	PostUserPassword(c *gin.Context)
	// Request a password reset. An email with a verification link will be sent to the user's address
	// (POST /user/password/reset)
	PostUserPasswordReset(c *gin.Context)
	// Verify tickets created by email verification, email passwordless authentication (magic link), or password reset
	// (GET /verify)
	GetVerify(c *gin.Context, params GetVerifyParams)
	// Get version
	// (GET /version)
	GetVersion(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetWellKnownJwksJson operation middleware
func (siw *ServerInterfaceWrapper) GetWellKnownJwksJson(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWellKnownJwksJson(c)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthz(c)
}

// HeadHealthz operation middleware
func (siw *ServerInterfaceWrapper) HeadHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HeadHealthz(c)
}

// PostLinkIdtoken operation middleware
func (siw *ServerInterfaceWrapper) PostLinkIdtoken(c *gin.Context) {

	c.Set(BearerAuthElevatedScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostLinkIdtoken(c)
}

// GetMfaTotpGenerate operation middleware
func (siw *ServerInterfaceWrapper) GetMfaTotpGenerate(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMfaTotpGenerate(c)
}

// PostPat operation middleware
func (siw *ServerInterfaceWrapper) PostPat(c *gin.Context) {

	c.Set(BearerAuthElevatedScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPat(c)
}

// PostSigninAnonymous operation middleware
func (siw *ServerInterfaceWrapper) PostSigninAnonymous(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSigninAnonymous(c)
}

// PostSigninEmailPassword operation middleware
func (siw *ServerInterfaceWrapper) PostSigninEmailPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSigninEmailPassword(c)
}

// PostSigninIdtoken operation middleware
func (siw *ServerInterfaceWrapper) PostSigninIdtoken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSigninIdtoken(c)
}

// PostSigninMfaTotp operation middleware
func (siw *ServerInterfaceWrapper) PostSigninMfaTotp(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSigninMfaTotp(c)
}

// PostSigninOtpEmail operation middleware
func (siw *ServerInterfaceWrapper) PostSigninOtpEmail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSigninOtpEmail(c)
}

// PostSigninOtpEmailVerify operation middleware
func (siw *ServerInterfaceWrapper) PostSigninOtpEmailVerify(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSigninOtpEmailVerify(c)
}

// PostSigninPasswordlessEmail operation middleware
func (siw *ServerInterfaceWrapper) PostSigninPasswordlessEmail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSigninPasswordlessEmail(c)
}

// PostSigninPat operation middleware
func (siw *ServerInterfaceWrapper) PostSigninPat(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSigninPat(c)
}

// GetSigninProviderProvider operation middleware
func (siw *ServerInterfaceWrapper) GetSigninProviderProvider(c *gin.Context) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider GetSigninProviderProviderParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", c.Param("provider"), &provider, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter provider: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSigninProviderProviderParams

	// ------------- Optional query parameter "allowedRoles" -------------

	err = runtime.BindQueryParameter("form", true, false, "allowedRoles", c.Request.URL.Query(), &params.AllowedRoles)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter allowedRoles: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "defaultRole" -------------

	err = runtime.BindQueryParameter("form", true, false, "defaultRole", c.Request.URL.Query(), &params.DefaultRole)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter defaultRole: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "displayName" -------------

	err = runtime.BindQueryParameter("form", true, false, "displayName", c.Request.URL.Query(), &params.DisplayName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter displayName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "locale" -------------

	err = runtime.BindQueryParameter("form", true, false, "locale", c.Request.URL.Query(), &params.Locale)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter locale: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "metadata" -------------

	err = runtime.BindQueryParameter("form", true, false, "metadata", c.Request.URL.Query(), &params.Metadata)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter metadata: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "redirectTo" -------------

	err = runtime.BindQueryParameter("form", true, false, "redirectTo", c.Request.URL.Query(), &params.RedirectTo)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter redirectTo: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "connect" -------------

	err = runtime.BindQueryParameter("form", true, false, "connect", c.Request.URL.Query(), &params.Connect)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter connect: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSigninProviderProvider(c, provider, params)
}

// GetSigninProviderProviderCallback operation middleware
func (siw *ServerInterfaceWrapper) GetSigninProviderProviderCallback(c *gin.Context) {

	var err error

	// ------------- Path parameter "provider" -------------
	var provider GetSigninProviderProviderCallbackParamsProvider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", c.Param("provider"), &provider, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter provider: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSigninProviderProviderCallbackParams

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument code is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", c.Request.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument state is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", c.Request.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameter("form", true, false, "error", c.Request.URL.Query(), &params.Error)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter error: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "error_description" -------------

	err = runtime.BindQueryParameter("form", true, false, "error_description", c.Request.URL.Query(), &params.ErrorDescription)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter error_description: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "error_uri" -------------

	err = runtime.BindQueryParameter("form", true, false, "error_uri", c.Request.URL.Query(), &params.ErrorUri)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter error_uri: %w", err), http.StatusBadRequest)
		return
	}

	{
		var cookie string

		if cookie, err = c.Cookie("nhostAuthProviderSignInData"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "nhostAuthProviderSignInData", cookie, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter nhostAuthProviderSignInData: %w", err), http.StatusBadRequest)
				return
			}
			params.NhostAuthProviderSignInData = value

		} else {
			siw.ErrorHandler(c, fmt.Errorf("Query argument nhostAuthProviderSignInData is required, but not found"), http.StatusBadRequest)
			return
		}
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSigninProviderProviderCallback(c, provider, params)
}

// PostSigninWebauthn operation middleware
func (siw *ServerInterfaceWrapper) PostSigninWebauthn(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSigninWebauthn(c)
}

// PostSigninWebauthnVerify operation middleware
func (siw *ServerInterfaceWrapper) PostSigninWebauthnVerify(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSigninWebauthnVerify(c)
}

// PostSignupEmailPassword operation middleware
func (siw *ServerInterfaceWrapper) PostSignupEmailPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSignupEmailPassword(c)
}

// PostSignupWebauthn operation middleware
func (siw *ServerInterfaceWrapper) PostSignupWebauthn(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSignupWebauthn(c)
}

// PostSignupWebauthnVerify operation middleware
func (siw *ServerInterfaceWrapper) PostSignupWebauthnVerify(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSignupWebauthnVerify(c)
}

// PostToken operation middleware
func (siw *ServerInterfaceWrapper) PostToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostToken(c)
}

// PostUserDeanonymize operation middleware
func (siw *ServerInterfaceWrapper) PostUserDeanonymize(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUserDeanonymize(c)
}

// PostUserEmailChange operation middleware
func (siw *ServerInterfaceWrapper) PostUserEmailChange(c *gin.Context) {

	c.Set(BearerAuthElevatedScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUserEmailChange(c)
}

// PostUserEmailSendVerificationEmail operation middleware
func (siw *ServerInterfaceWrapper) PostUserEmailSendVerificationEmail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUserEmailSendVerificationEmail(c)
}

// PostUserMfa operation middleware
func (siw *ServerInterfaceWrapper) PostUserMfa(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUserMfa(c)
}

// PostUserPassword operation middleware
func (siw *ServerInterfaceWrapper) PostUserPassword(c *gin.Context) {

	c.Set(BearerAuthElevatedScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUserPassword(c)
}

// PostUserPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) PostUserPasswordReset(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUserPasswordReset(c)
}

// GetVerify operation middleware
func (siw *ServerInterfaceWrapper) GetVerify(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVerifyParams

	// ------------- Required query parameter "ticket" -------------

	if paramValue := c.Query("ticket"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument ticket is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "ticket", c.Request.URL.Query(), &params.Ticket)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ticket: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", c.Request.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter type: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "redirectTo" -------------

	if paramValue := c.Query("redirectTo"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument redirectTo is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "redirectTo", c.Request.URL.Query(), &params.RedirectTo)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter redirectTo: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVerify(c, params)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/.well-known/jwks.json", wrapper.GetWellKnownJwksJson)
	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz)
	router.HEAD(options.BaseURL+"/healthz", wrapper.HeadHealthz)
	router.POST(options.BaseURL+"/link/idtoken", wrapper.PostLinkIdtoken)
	router.GET(options.BaseURL+"/mfa/totp/generate", wrapper.GetMfaTotpGenerate)
	router.POST(options.BaseURL+"/pat", wrapper.PostPat)
	router.POST(options.BaseURL+"/signin/anonymous", wrapper.PostSigninAnonymous)
	router.POST(options.BaseURL+"/signin/email-password", wrapper.PostSigninEmailPassword)
	router.POST(options.BaseURL+"/signin/idtoken", wrapper.PostSigninIdtoken)
	router.POST(options.BaseURL+"/signin/mfa/totp", wrapper.PostSigninMfaTotp)
	router.POST(options.BaseURL+"/signin/otp/email", wrapper.PostSigninOtpEmail)
	router.POST(options.BaseURL+"/signin/otp/email/verify", wrapper.PostSigninOtpEmailVerify)
	router.POST(options.BaseURL+"/signin/passwordless/email", wrapper.PostSigninPasswordlessEmail)
	router.POST(options.BaseURL+"/signin/pat", wrapper.PostSigninPat)
	router.GET(options.BaseURL+"/signin/provider/:provider", wrapper.GetSigninProviderProvider)
	router.GET(options.BaseURL+"/signin/provider/:provider/callback", wrapper.GetSigninProviderProviderCallback)
	router.POST(options.BaseURL+"/signin/webauthn", wrapper.PostSigninWebauthn)
	router.POST(options.BaseURL+"/signin/webauthn/verify", wrapper.PostSigninWebauthnVerify)
	router.POST(options.BaseURL+"/signup/email-password", wrapper.PostSignupEmailPassword)
	router.POST(options.BaseURL+"/signup/webauthn", wrapper.PostSignupWebauthn)
	router.POST(options.BaseURL+"/signup/webauthn/verify", wrapper.PostSignupWebauthnVerify)
	router.POST(options.BaseURL+"/token", wrapper.PostToken)
	router.POST(options.BaseURL+"/user/deanonymize", wrapper.PostUserDeanonymize)
	router.POST(options.BaseURL+"/user/email/change", wrapper.PostUserEmailChange)
	router.POST(options.BaseURL+"/user/email/send-verification-email", wrapper.PostUserEmailSendVerificationEmail)
	router.POST(options.BaseURL+"/user/mfa", wrapper.PostUserMfa)
	router.POST(options.BaseURL+"/user/password", wrapper.PostUserPassword)
	router.POST(options.BaseURL+"/user/password/reset", wrapper.PostUserPasswordReset)
	router.GET(options.BaseURL+"/verify", wrapper.GetVerify)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion)
}

type GetWellKnownJwksJsonRequestObject struct {
}

type GetWellKnownJwksJsonResponseObject interface {
	VisitGetWellKnownJwksJsonResponse(w http.ResponseWriter) error
}

type GetWellKnownJwksJson200JSONResponse JWKSet

func (response GetWellKnownJwksJson200JSONResponse) VisitGetWellKnownJwksJsonResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse OKResponse

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type HeadHealthzRequestObject struct {
}

type HeadHealthzResponseObject interface {
	VisitHeadHealthzResponse(w http.ResponseWriter) error
}

type HeadHealthz200Response struct {
}

func (response HeadHealthz200Response) VisitHeadHealthzResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PostLinkIdtokenRequestObject struct {
	Body *PostLinkIdtokenJSONRequestBody
}

type PostLinkIdtokenResponseObject interface {
	VisitPostLinkIdtokenResponse(w http.ResponseWriter) error
}

type PostLinkIdtoken200JSONResponse OKResponse

func (response PostLinkIdtoken200JSONResponse) VisitPostLinkIdtokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMfaTotpGenerateRequestObject struct {
}

type GetMfaTotpGenerateResponseObject interface {
	VisitGetMfaTotpGenerateResponse(w http.ResponseWriter) error
}

type GetMfaTotpGenerate200JSONResponse TotpGenerateResponse

func (response GetMfaTotpGenerate200JSONResponse) VisitGetMfaTotpGenerateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostPatRequestObject struct {
	Body *PostPatJSONRequestBody
}

type PostPatResponseObject interface {
	VisitPostPatResponse(w http.ResponseWriter) error
}

type PostPat200JSONResponse CreatePATResponse

func (response PostPat200JSONResponse) VisitPostPatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSigninAnonymousRequestObject struct {
	Body *PostSigninAnonymousJSONRequestBody
}

type PostSigninAnonymousResponseObject interface {
	VisitPostSigninAnonymousResponse(w http.ResponseWriter) error
}

type PostSigninAnonymous200JSONResponse SessionPayload

func (response PostSigninAnonymous200JSONResponse) VisitPostSigninAnonymousResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSigninEmailPasswordRequestObject struct {
	Body *PostSigninEmailPasswordJSONRequestBody
}

type PostSigninEmailPasswordResponseObject interface {
	VisitPostSigninEmailPasswordResponse(w http.ResponseWriter) error
}

type PostSigninEmailPassword200JSONResponse SignInEmailPasswordResponse

func (response PostSigninEmailPassword200JSONResponse) VisitPostSigninEmailPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSigninIdtokenRequestObject struct {
	Body *PostSigninIdtokenJSONRequestBody
}

type PostSigninIdtokenResponseObject interface {
	VisitPostSigninIdtokenResponse(w http.ResponseWriter) error
}

type PostSigninIdtoken200JSONResponse SessionPayload

func (response PostSigninIdtoken200JSONResponse) VisitPostSigninIdtokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSigninMfaTotpRequestObject struct {
	Body *PostSigninMfaTotpJSONRequestBody
}

type PostSigninMfaTotpResponseObject interface {
	VisitPostSigninMfaTotpResponse(w http.ResponseWriter) error
}

type PostSigninMfaTotp200JSONResponse SessionPayload

func (response PostSigninMfaTotp200JSONResponse) VisitPostSigninMfaTotpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSigninOtpEmailRequestObject struct {
	Body *PostSigninOtpEmailJSONRequestBody
}

type PostSigninOtpEmailResponseObject interface {
	VisitPostSigninOtpEmailResponse(w http.ResponseWriter) error
}

type PostSigninOtpEmail200JSONResponse OKResponse

func (response PostSigninOtpEmail200JSONResponse) VisitPostSigninOtpEmailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSigninOtpEmailVerifyRequestObject struct {
	Body *PostSigninOtpEmailVerifyJSONRequestBody
}

type PostSigninOtpEmailVerifyResponseObject interface {
	VisitPostSigninOtpEmailVerifyResponse(w http.ResponseWriter) error
}

type PostSigninOtpEmailVerify200JSONResponse SignInOTPEmailVerifyResponse

func (response PostSigninOtpEmailVerify200JSONResponse) VisitPostSigninOtpEmailVerifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSigninPasswordlessEmailRequestObject struct {
	Body *PostSigninPasswordlessEmailJSONRequestBody
}

type PostSigninPasswordlessEmailResponseObject interface {
	VisitPostSigninPasswordlessEmailResponse(w http.ResponseWriter) error
}

type PostSigninPasswordlessEmail200JSONResponse OKResponse

func (response PostSigninPasswordlessEmail200JSONResponse) VisitPostSigninPasswordlessEmailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSigninPatRequestObject struct {
	Body *PostSigninPatJSONRequestBody
}

type PostSigninPatResponseObject interface {
	VisitPostSigninPatResponse(w http.ResponseWriter) error
}

type PostSigninPat200JSONResponse SessionPayload

func (response PostSigninPat200JSONResponse) VisitPostSigninPatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSigninProviderProviderRequestObject struct {
	Provider GetSigninProviderProviderParamsProvider `json:"provider"`
	Params   GetSigninProviderProviderParams
}

type GetSigninProviderProviderResponseObject interface {
	VisitGetSigninProviderProviderResponse(w http.ResponseWriter) error
}

type GetSigninProviderProvider302ResponseHeaders struct {
	Location  string
	SetCookie string
}

type GetSigninProviderProvider302Response struct {
	Headers GetSigninProviderProvider302ResponseHeaders
}

func (response GetSigninProviderProvider302Response) VisitGetSigninProviderProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(302)
	return nil
}

type GetSigninProviderProviderCallbackRequestObject struct {
	Provider GetSigninProviderProviderCallbackParamsProvider `json:"provider"`
	Params   GetSigninProviderProviderCallbackParams
}

type GetSigninProviderProviderCallbackResponseObject interface {
	VisitGetSigninProviderProviderCallbackResponse(w http.ResponseWriter) error
}

type GetSigninProviderProviderCallback302ResponseHeaders struct {
	Location  string
	SetCookie string
}

type GetSigninProviderProviderCallback302Response struct {
	Headers GetSigninProviderProviderCallback302ResponseHeaders
}

func (response GetSigninProviderProviderCallback302Response) VisitGetSigninProviderProviderCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(302)
	return nil
}

type PostSigninWebauthnRequestObject struct {
	Body *PostSigninWebauthnJSONRequestBody
}

type PostSigninWebauthnResponseObject interface {
	VisitPostSigninWebauthnResponse(w http.ResponseWriter) error
}

type PostSigninWebauthn200JSONResponse SignInWebauthnResponse

func (response PostSigninWebauthn200JSONResponse) VisitPostSigninWebauthnResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSigninWebauthnVerifyRequestObject struct {
	Body *PostSigninWebauthnVerifyJSONRequestBody
}

type PostSigninWebauthnVerifyResponseObject interface {
	VisitPostSigninWebauthnVerifyResponse(w http.ResponseWriter) error
}

type PostSigninWebauthnVerify200JSONResponse SessionPayload

func (response PostSigninWebauthnVerify200JSONResponse) VisitPostSigninWebauthnVerifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSignupEmailPasswordRequestObject struct {
	Body *PostSignupEmailPasswordJSONRequestBody
}

type PostSignupEmailPasswordResponseObject interface {
	VisitPostSignupEmailPasswordResponse(w http.ResponseWriter) error
}

type PostSignupEmailPassword200JSONResponse SessionPayload

func (response PostSignupEmailPassword200JSONResponse) VisitPostSignupEmailPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSignupEmailPassword403JSONResponse ErrorResponse

func (response PostSignupEmailPassword403JSONResponse) VisitPostSignupEmailPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostSignupEmailPassword409JSONResponse ErrorResponse

func (response PostSignupEmailPassword409JSONResponse) VisitPostSignupEmailPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostSignupWebauthnRequestObject struct {
	Body *PostSignupWebauthnJSONRequestBody
}

type PostSignupWebauthnResponseObject interface {
	VisitPostSignupWebauthnResponse(w http.ResponseWriter) error
}

type PostSignupWebauthn200JSONResponse SignUpWebauthnResponse

func (response PostSignupWebauthn200JSONResponse) VisitPostSignupWebauthnResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSignupWebauthnVerifyRequestObject struct {
	Body *PostSignupWebauthnVerifyJSONRequestBody
}

type PostSignupWebauthnVerifyResponseObject interface {
	VisitPostSignupWebauthnVerifyResponse(w http.ResponseWriter) error
}

type PostSignupWebauthnVerify200JSONResponse SessionPayload

func (response PostSignupWebauthnVerify200JSONResponse) VisitPostSignupWebauthnVerifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostTokenRequestObject struct {
	Body *PostTokenJSONRequestBody
}

type PostTokenResponseObject interface {
	VisitPostTokenResponse(w http.ResponseWriter) error
}

type PostToken200JSONResponse Session

func (response PostToken200JSONResponse) VisitPostTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUserDeanonymizeRequestObject struct {
	Body *PostUserDeanonymizeJSONRequestBody
}

type PostUserDeanonymizeResponseObject interface {
	VisitPostUserDeanonymizeResponse(w http.ResponseWriter) error
}

type PostUserDeanonymize200JSONResponse OKResponse

func (response PostUserDeanonymize200JSONResponse) VisitPostUserDeanonymizeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUserEmailChangeRequestObject struct {
	Body *PostUserEmailChangeJSONRequestBody
}

type PostUserEmailChangeResponseObject interface {
	VisitPostUserEmailChangeResponse(w http.ResponseWriter) error
}

type PostUserEmailChange200JSONResponse OKResponse

func (response PostUserEmailChange200JSONResponse) VisitPostUserEmailChangeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUserEmailSendVerificationEmailRequestObject struct {
	Body *PostUserEmailSendVerificationEmailJSONRequestBody
}

type PostUserEmailSendVerificationEmailResponseObject interface {
	VisitPostUserEmailSendVerificationEmailResponse(w http.ResponseWriter) error
}

type PostUserEmailSendVerificationEmail200JSONResponse OKResponse

func (response PostUserEmailSendVerificationEmail200JSONResponse) VisitPostUserEmailSendVerificationEmailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUserMfaRequestObject struct {
	Body *PostUserMfaJSONRequestBody
}

type PostUserMfaResponseObject interface {
	VisitPostUserMfaResponse(w http.ResponseWriter) error
}

type PostUserMfa200JSONResponse OKResponse

func (response PostUserMfa200JSONResponse) VisitPostUserMfaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUserPasswordRequestObject struct {
	Body *PostUserPasswordJSONRequestBody
}

type PostUserPasswordResponseObject interface {
	VisitPostUserPasswordResponse(w http.ResponseWriter) error
}

type PostUserPassword200JSONResponse OKResponse

func (response PostUserPassword200JSONResponse) VisitPostUserPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUserPasswordResetRequestObject struct {
	Body *PostUserPasswordResetJSONRequestBody
}

type PostUserPasswordResetResponseObject interface {
	VisitPostUserPasswordResetResponse(w http.ResponseWriter) error
}

type PostUserPasswordReset200JSONResponse OKResponse

func (response PostUserPasswordReset200JSONResponse) VisitPostUserPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVerifyRequestObject struct {
	Params GetVerifyParams
}

type GetVerifyResponseObject interface {
	VisitGetVerifyResponse(w http.ResponseWriter) error
}

type GetVerify302ResponseHeaders struct {
	Location string
}

type GetVerify302Response struct {
	Headers GetVerify302ResponseHeaders
}

func (response GetVerify302Response) VisitGetVerifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse struct {
	Version string `json:"version"`
}

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get public keys for JWT verification in JWK Set format
	// (GET /.well-known/jwks.json)
	GetWellKnownJwksJson(ctx context.Context, request GetWellKnownJwksJsonRequestObject) (GetWellKnownJwksJsonResponseObject, error)
	// Health check
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// Health check
	// (HEAD /healthz)
	HeadHealthz(ctx context.Context, request HeadHealthzRequestObject) (HeadHealthzResponseObject, error)
	// Link a user account with the provider's account using an id token
	// (POST /link/idtoken)
	PostLinkIdtoken(ctx context.Context, request PostLinkIdtokenRequestObject) (PostLinkIdtokenResponseObject, error)
	// Generate TOTP secret for MFA setup
	// (GET /mfa/totp/generate)
	GetMfaTotpGenerate(ctx context.Context, request GetMfaTotpGenerateRequestObject) (GetMfaTotpGenerateResponseObject, error)
	// Create a Personal Access Token (PAT)
	// (POST /pat)
	PostPat(ctx context.Context, request PostPatRequestObject) (PostPatResponseObject, error)
	// Sign in anonymously
	// (POST /signin/anonymous)
	PostSigninAnonymous(ctx context.Context, request PostSigninAnonymousRequestObject) (PostSigninAnonymousResponseObject, error)
	// Sign in with email and password
	// (POST /signin/email-password)
	PostSigninEmailPassword(ctx context.Context, request PostSigninEmailPasswordRequestObject) (PostSigninEmailPasswordResponseObject, error)
	// Sign in with in an id token
	// (POST /signin/idtoken)
	PostSigninIdtoken(ctx context.Context, request PostSigninIdtokenRequestObject) (PostSigninIdtokenResponseObject, error)
	// Verify TOTP and return a session if validation is successful
	// (POST /signin/mfa/totp)
	PostSigninMfaTotp(ctx context.Context, request PostSigninMfaTotpRequestObject) (PostSigninMfaTotpResponseObject, error)
	// Sign in with a one time password sent to user's email. If the user doesn't exist, it will be created. The options object is optional and can be used to configure the user's when signing up a new user. It is ignored if the user already exists.
	// (POST /signin/otp/email)
	PostSigninOtpEmail(ctx context.Context, request PostSigninOtpEmailRequestObject) (PostSigninOtpEmailResponseObject, error)
	// Verify OTP and return a session if validation is successful
	// (POST /signin/otp/email/verify)
	PostSigninOtpEmailVerify(ctx context.Context, request PostSigninOtpEmailVerifyRequestObject) (PostSigninOtpEmailVerifyResponseObject, error)
	// Sign in with magic link sent to user's email. If the user doesn't exist, it will be created. The options object is optional and can be used to configure the user's when signing up a new user. It is ignored if the user already exists.
	// (POST /signin/passwordless/email)
	PostSigninPasswordlessEmail(ctx context.Context, request PostSigninPasswordlessEmailRequestObject) (PostSigninPasswordlessEmailResponseObject, error)
	// Sign in with Personal Access Token (PAT)
	// (POST /signin/pat)
	PostSigninPat(ctx context.Context, request PostSigninPatRequestObject) (PostSigninPatResponseObject, error)
	// Sign in with an oauth2 provider
	// (GET /signin/provider/{provider})
	GetSigninProviderProvider(ctx context.Context, request GetSigninProviderProviderRequestObject) (GetSigninProviderProviderResponseObject, error)
	// Callback for oauth2 provider
	// (GET /signin/provider/{provider}/callback)
	GetSigninProviderProviderCallback(ctx context.Context, request GetSigninProviderProviderCallbackRequestObject) (GetSigninProviderProviderCallbackResponseObject, error)
	// Signin with webauthn
	// (POST /signin/webauthn)
	PostSigninWebauthn(ctx context.Context, request PostSigninWebauthnRequestObject) (PostSigninWebauthnResponseObject, error)
	// Verify webauthn signin
	// (POST /signin/webauthn/verify)
	PostSigninWebauthnVerify(ctx context.Context, request PostSigninWebauthnVerifyRequestObject) (PostSigninWebauthnVerifyResponseObject, error)
	// Signup with email and password
	// (POST /signup/email-password)
	PostSignupEmailPassword(ctx context.Context, request PostSignupEmailPasswordRequestObject) (PostSignupEmailPasswordResponseObject, error)
	// Signup with webauthn
	// (POST /signup/webauthn)
	PostSignupWebauthn(ctx context.Context, request PostSignupWebauthnRequestObject) (PostSignupWebauthnResponseObject, error)
	// Verify webauthn signup
	// (POST /signup/webauthn/verify)
	PostSignupWebauthnVerify(ctx context.Context, request PostSignupWebauthnVerifyRequestObject) (PostSignupWebauthnVerifyResponseObject, error)
	// Refresh the JWT access token
	// (POST /token)
	PostToken(ctx context.Context, request PostTokenRequestObject) (PostTokenResponseObject, error)
	// Deanonymize an anonymous user in adding missing email or email+password, depending on the chosen authentication method. Will send a confirmation email if the server is configured to do so
	// (POST /user/deanonymize)
	PostUserDeanonymize(ctx context.Context, request PostUserDeanonymizeRequestObject) (PostUserDeanonymizeResponseObject, error)
	// Change user email
	// (POST /user/email/change)
	PostUserEmailChange(ctx context.Context, request PostUserEmailChangeRequestObject) (PostUserEmailChangeResponseObject, error)
	// Send email verification email
	// (POST /user/email/send-verification-email)
	PostUserEmailSendVerificationEmail(ctx context.Context, request PostUserEmailSendVerificationEmailRequestObject) (PostUserEmailSendVerificationEmailResponseObject, error)
	// Activate/deactivate Multi-factor authentication
	// (POST /user/mfa)
	PostUserMfa(ctx context.Context, request PostUserMfaRequestObject) (PostUserMfaResponseObject, error)
	// Change user password. The user must be authenticated or provide a ticket
	// (POST /user/password)
	PostUserPassword(ctx context.Context, request PostUserPasswordRequestObject) (PostUserPasswordResponseObject, error)
	// Request a password reset. An email with a verification link will be sent to the user's address
	// (POST /user/password/reset)
	PostUserPasswordReset(ctx context.Context, request PostUserPasswordResetRequestObject) (PostUserPasswordResetResponseObject, error)
	// Verify tickets created by email verification, email passwordless authentication (magic link), or password reset
	// (GET /verify)
	GetVerify(ctx context.Context, request GetVerifyRequestObject) (GetVerifyResponseObject, error)
	// Get version
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetWellKnownJwksJson operation middleware
func (sh *strictHandler) GetWellKnownJwksJson(ctx *gin.Context) {
	var request GetWellKnownJwksJsonRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWellKnownJwksJson(ctx, request.(GetWellKnownJwksJsonRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWellKnownJwksJson")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetWellKnownJwksJsonResponseObject); ok {
		if err := validResponse.VisitGetWellKnownJwksJsonResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(ctx *gin.Context) {
	var request GetHealthzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// HeadHealthz operation middleware
func (sh *strictHandler) HeadHealthz(ctx *gin.Context) {
	var request HeadHealthzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.HeadHealthz(ctx, request.(HeadHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HeadHealthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(HeadHealthzResponseObject); ok {
		if err := validResponse.VisitHeadHealthzResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostLinkIdtoken operation middleware
func (sh *strictHandler) PostLinkIdtoken(ctx *gin.Context) {
	var request PostLinkIdtokenRequestObject

	var body PostLinkIdtokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostLinkIdtoken(ctx, request.(PostLinkIdtokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLinkIdtoken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostLinkIdtokenResponseObject); ok {
		if err := validResponse.VisitPostLinkIdtokenResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMfaTotpGenerate operation middleware
func (sh *strictHandler) GetMfaTotpGenerate(ctx *gin.Context) {
	var request GetMfaTotpGenerateRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMfaTotpGenerate(ctx, request.(GetMfaTotpGenerateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMfaTotpGenerate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetMfaTotpGenerateResponseObject); ok {
		if err := validResponse.VisitGetMfaTotpGenerateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostPat operation middleware
func (sh *strictHandler) PostPat(ctx *gin.Context) {
	var request PostPatRequestObject

	var body PostPatJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostPat(ctx, request.(PostPatRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostPat")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostPatResponseObject); ok {
		if err := validResponse.VisitPostPatResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSigninAnonymous operation middleware
func (sh *strictHandler) PostSigninAnonymous(ctx *gin.Context) {
	var request PostSigninAnonymousRequestObject

	var body PostSigninAnonymousJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			ctx.Status(http.StatusBadRequest)
			ctx.Error(err)
			return
		}
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSigninAnonymous(ctx, request.(PostSigninAnonymousRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSigninAnonymous")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSigninAnonymousResponseObject); ok {
		if err := validResponse.VisitPostSigninAnonymousResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSigninEmailPassword operation middleware
func (sh *strictHandler) PostSigninEmailPassword(ctx *gin.Context) {
	var request PostSigninEmailPasswordRequestObject

	var body PostSigninEmailPasswordJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSigninEmailPassword(ctx, request.(PostSigninEmailPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSigninEmailPassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSigninEmailPasswordResponseObject); ok {
		if err := validResponse.VisitPostSigninEmailPasswordResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSigninIdtoken operation middleware
func (sh *strictHandler) PostSigninIdtoken(ctx *gin.Context) {
	var request PostSigninIdtokenRequestObject

	var body PostSigninIdtokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSigninIdtoken(ctx, request.(PostSigninIdtokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSigninIdtoken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSigninIdtokenResponseObject); ok {
		if err := validResponse.VisitPostSigninIdtokenResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSigninMfaTotp operation middleware
func (sh *strictHandler) PostSigninMfaTotp(ctx *gin.Context) {
	var request PostSigninMfaTotpRequestObject

	var body PostSigninMfaTotpJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSigninMfaTotp(ctx, request.(PostSigninMfaTotpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSigninMfaTotp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSigninMfaTotpResponseObject); ok {
		if err := validResponse.VisitPostSigninMfaTotpResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSigninOtpEmail operation middleware
func (sh *strictHandler) PostSigninOtpEmail(ctx *gin.Context) {
	var request PostSigninOtpEmailRequestObject

	var body PostSigninOtpEmailJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSigninOtpEmail(ctx, request.(PostSigninOtpEmailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSigninOtpEmail")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSigninOtpEmailResponseObject); ok {
		if err := validResponse.VisitPostSigninOtpEmailResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSigninOtpEmailVerify operation middleware
func (sh *strictHandler) PostSigninOtpEmailVerify(ctx *gin.Context) {
	var request PostSigninOtpEmailVerifyRequestObject

	var body PostSigninOtpEmailVerifyJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSigninOtpEmailVerify(ctx, request.(PostSigninOtpEmailVerifyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSigninOtpEmailVerify")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSigninOtpEmailVerifyResponseObject); ok {
		if err := validResponse.VisitPostSigninOtpEmailVerifyResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSigninPasswordlessEmail operation middleware
func (sh *strictHandler) PostSigninPasswordlessEmail(ctx *gin.Context) {
	var request PostSigninPasswordlessEmailRequestObject

	var body PostSigninPasswordlessEmailJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSigninPasswordlessEmail(ctx, request.(PostSigninPasswordlessEmailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSigninPasswordlessEmail")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSigninPasswordlessEmailResponseObject); ok {
		if err := validResponse.VisitPostSigninPasswordlessEmailResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSigninPat operation middleware
func (sh *strictHandler) PostSigninPat(ctx *gin.Context) {
	var request PostSigninPatRequestObject

	var body PostSigninPatJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSigninPat(ctx, request.(PostSigninPatRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSigninPat")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSigninPatResponseObject); ok {
		if err := validResponse.VisitPostSigninPatResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSigninProviderProvider operation middleware
func (sh *strictHandler) GetSigninProviderProvider(ctx *gin.Context, provider GetSigninProviderProviderParamsProvider, params GetSigninProviderProviderParams) {
	var request GetSigninProviderProviderRequestObject

	request.Provider = provider
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSigninProviderProvider(ctx, request.(GetSigninProviderProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSigninProviderProvider")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetSigninProviderProviderResponseObject); ok {
		if err := validResponse.VisitGetSigninProviderProviderResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSigninProviderProviderCallback operation middleware
func (sh *strictHandler) GetSigninProviderProviderCallback(ctx *gin.Context, provider GetSigninProviderProviderCallbackParamsProvider, params GetSigninProviderProviderCallbackParams) {
	var request GetSigninProviderProviderCallbackRequestObject

	request.Provider = provider
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSigninProviderProviderCallback(ctx, request.(GetSigninProviderProviderCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSigninProviderProviderCallback")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetSigninProviderProviderCallbackResponseObject); ok {
		if err := validResponse.VisitGetSigninProviderProviderCallbackResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSigninWebauthn operation middleware
func (sh *strictHandler) PostSigninWebauthn(ctx *gin.Context) {
	var request PostSigninWebauthnRequestObject

	var body PostSigninWebauthnJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSigninWebauthn(ctx, request.(PostSigninWebauthnRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSigninWebauthn")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSigninWebauthnResponseObject); ok {
		if err := validResponse.VisitPostSigninWebauthnResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSigninWebauthnVerify operation middleware
func (sh *strictHandler) PostSigninWebauthnVerify(ctx *gin.Context) {
	var request PostSigninWebauthnVerifyRequestObject

	var body PostSigninWebauthnVerifyJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSigninWebauthnVerify(ctx, request.(PostSigninWebauthnVerifyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSigninWebauthnVerify")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSigninWebauthnVerifyResponseObject); ok {
		if err := validResponse.VisitPostSigninWebauthnVerifyResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSignupEmailPassword operation middleware
func (sh *strictHandler) PostSignupEmailPassword(ctx *gin.Context) {
	var request PostSignupEmailPasswordRequestObject

	var body PostSignupEmailPasswordJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSignupEmailPassword(ctx, request.(PostSignupEmailPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSignupEmailPassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSignupEmailPasswordResponseObject); ok {
		if err := validResponse.VisitPostSignupEmailPasswordResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSignupWebauthn operation middleware
func (sh *strictHandler) PostSignupWebauthn(ctx *gin.Context) {
	var request PostSignupWebauthnRequestObject

	var body PostSignupWebauthnJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSignupWebauthn(ctx, request.(PostSignupWebauthnRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSignupWebauthn")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSignupWebauthnResponseObject); ok {
		if err := validResponse.VisitPostSignupWebauthnResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostSignupWebauthnVerify operation middleware
func (sh *strictHandler) PostSignupWebauthnVerify(ctx *gin.Context) {
	var request PostSignupWebauthnVerifyRequestObject

	var body PostSignupWebauthnVerifyJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSignupWebauthnVerify(ctx, request.(PostSignupWebauthnVerifyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSignupWebauthnVerify")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostSignupWebauthnVerifyResponseObject); ok {
		if err := validResponse.VisitPostSignupWebauthnVerifyResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostToken operation middleware
func (sh *strictHandler) PostToken(ctx *gin.Context) {
	var request PostTokenRequestObject

	var body PostTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostToken(ctx, request.(PostTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostTokenResponseObject); ok {
		if err := validResponse.VisitPostTokenResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostUserDeanonymize operation middleware
func (sh *strictHandler) PostUserDeanonymize(ctx *gin.Context) {
	var request PostUserDeanonymizeRequestObject

	var body PostUserDeanonymizeJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUserDeanonymize(ctx, request.(PostUserDeanonymizeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUserDeanonymize")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostUserDeanonymizeResponseObject); ok {
		if err := validResponse.VisitPostUserDeanonymizeResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostUserEmailChange operation middleware
func (sh *strictHandler) PostUserEmailChange(ctx *gin.Context) {
	var request PostUserEmailChangeRequestObject

	var body PostUserEmailChangeJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUserEmailChange(ctx, request.(PostUserEmailChangeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUserEmailChange")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostUserEmailChangeResponseObject); ok {
		if err := validResponse.VisitPostUserEmailChangeResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostUserEmailSendVerificationEmail operation middleware
func (sh *strictHandler) PostUserEmailSendVerificationEmail(ctx *gin.Context) {
	var request PostUserEmailSendVerificationEmailRequestObject

	var body PostUserEmailSendVerificationEmailJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUserEmailSendVerificationEmail(ctx, request.(PostUserEmailSendVerificationEmailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUserEmailSendVerificationEmail")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostUserEmailSendVerificationEmailResponseObject); ok {
		if err := validResponse.VisitPostUserEmailSendVerificationEmailResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostUserMfa operation middleware
func (sh *strictHandler) PostUserMfa(ctx *gin.Context) {
	var request PostUserMfaRequestObject

	var body PostUserMfaJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUserMfa(ctx, request.(PostUserMfaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUserMfa")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostUserMfaResponseObject); ok {
		if err := validResponse.VisitPostUserMfaResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostUserPassword operation middleware
func (sh *strictHandler) PostUserPassword(ctx *gin.Context) {
	var request PostUserPasswordRequestObject

	var body PostUserPasswordJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUserPassword(ctx, request.(PostUserPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUserPassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostUserPasswordResponseObject); ok {
		if err := validResponse.VisitPostUserPasswordResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostUserPasswordReset operation middleware
func (sh *strictHandler) PostUserPasswordReset(ctx *gin.Context) {
	var request PostUserPasswordResetRequestObject

	var body PostUserPasswordResetJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUserPasswordReset(ctx, request.(PostUserPasswordResetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUserPasswordReset")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostUserPasswordResetResponseObject); ok {
		if err := validResponse.VisitPostUserPasswordResetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVerify operation middleware
func (sh *strictHandler) GetVerify(ctx *gin.Context, params GetVerifyParams) {
	var request GetVerifyRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetVerify(ctx, request.(GetVerifyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVerify")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetVerifyResponseObject); ok {
		if err := validResponse.VisitGetVerifyResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(ctx *gin.Context) {
	var request GetVersionRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x963LcNpbwq6A4+crJN81uRfbMJkqlajW2k8hXjbs9/mFrt9DkYRMWCTAAqHbHq3ff",
	"woUkSIJ9s1pSPJsfcYskwINzx7mAn4OI5QWjQKUITj4HKeAYuP75BmLCIZIvWIQlYVRdi0FEnBTmz+Dt",
	"mxdIMsTtg0iyYBRw+L0kHOLgRPISRoGIUsixGpwwnmMZnAQlJ8EokKsCgpNASE7oIri+vh4FBeY4B9kB",
	"YMb+WQJf9d8/w3wBEikwEsaRTKGGJRgFRD3yux45CijO1ct4PeVaSHd5DXzCeZGpyVMpC3EymeSrEBfF",
	"OGL5JMIySsPqaTXdaBMaRsGULCih55xdkRi4gafgEGHZwNqBMAWkVohYosETLCI4Q0U1hUVGgWXa4MK5",
	"O4wJoGUenLwPcKHWOAoWRKblXP1gbKGvZIReQkxocOFby4xElyCH6KdvDpBKVje3JlM1oKHIFXCSrJ7m",
	"mGQnn+x/wTCYs1UBDqgbcL4qanwbWMfoST1mhChDGaML4KgUEA8tUkGyZkm9d6jlWZKAWta/9ArVVfXX",
	"Y0YTwvPHKaYLPa/hJCzEkvE4AyECJWTmzzcgQCqqNfjSk4Qaa8QKvVdODbxaSB9zwBLOT2dv4PcShFTX",
	"cBwTNRhn55wVwCUBEZwkOBMwUmxXX/ocwKeCcBCnsr/4p+qWBgLFWNZ4OD+duUKkboWS5NCHdBTkIHGM",
	"JR4GylC2xsDnijD5KiywwrYiXjhfmUu4KMIoI2pq+y42/6jUgEJKw6fvnWVd9B4duTgTBaMCdkQaifvY",
	"OnvSRlBD1OPo4d/mf08ehtGj+Y/hox/gYfjjf/yAw/hRfJR8Hz86huNHmi2kBK6m+vBh/v4o/BGHycXn",
	"H64/fJiH9Z+Prgd/u6O+P1bDfBQpgAu1xtMoAiFm7BI8duUer6BDZ6IE27cmH9mfcs74niQHNdYjI+oy",
	"ilgMSKZYIhIDlSQhIDQrKK1tBRmZGRr1EUOCy0yGnGUQ5qWQ4RxCQkOcZWwJsb6u1EVMBJ5nEIdA44IR",
	"Kt1rpdD2w+gNnHHA8UpNUgroXTZqRavChPE5iWOgIaaMrnJWCq0gFflwFgrgV8DDCmJCr3BG4tBMV6kv",
	"5wa3qmcUZCzCGYSUyWodjsILJWOhSBmX7kVCw5TMi1DpiTnWcDdeQmcmjav2JaViyyKsMKI0Bq1WWqFH",
	"/WOGtVZrgDdqpllKwkGkodRc1FyvtX+N+jzBoWSyUMaE6V+hgIiDO5u9rx9dFQb0hJVUgalHVLTBkSRX",
	"4IwUEkv1N8OltNCEEGm7EiaYmJWamwVnCckgTED5OvbmhVcbC4EX0Ofi38ocU5RwAjTOVoZTUfW0ZyIF",
	"XCk888xm58jctJMoyWhmUAy2AN6TYjtfA+HIyptPis9iLeGue7ZWjnselHGcfAh69u75jmoBZwv1T28m",
	"8F69NIajf12uvNep92opfLN3UKoAU2CYl5pXqAnNcB9en717PoVd3YdLWBmLKCHXP77hkAQnwV8mzbZm",
	"Yr2ViUJvY7kx53jVg1tP6APvBaGXlvT7eTokHrB2p4ox0NkTVMl8nw6MRh6xeaUua+8SxaV6FillhAhV",
	"jn9knL2+AXb4dh2yumzeRZS7t4iHbd7LX04fpzjLgC7gHK8yhuMd8WY130aOs8/5gHj9fGurW0nr6+de",
	"CX2tcS+anemOi+GtgTe/dewt/Y2xJ1/At9yZoc+Ddn40s7z7Z3DaWivy8csUhLABj110cdul7fGOc/+p",
	"2R6c0VZYhFD590ceazXakgZaf1SqQJlm5Qta749xtEyBIjuTekI5iM/e3eO9grvqs3jTurWZuacr0X7g",
	"BoX7Vni0rMtTAxzU4Y4e2tYw+H4KWTTSsW49lRB51dKULOgZ1YGZ8zocsVf8QE3hsalIu7HI3Hb54iNL",
	"6VjkRKb/SVMm5JgwV7FWA/p2s9p2eN5V3VM78JxQkpc5eoiiFHMc6WCmC8BU8iO60Kv+i9p//Pjof/6f",
	"cj3xpxdAFzINTv52NApyQqs/H27SZxXMNYgX22J8r61onuBNtPdZfeW33xjnfA2eGDO+xEZskAV9W1jH",
	"4w48OIPwlwmeMVnsh3C1C+3h7DUFJEkOyNnQ93DUOH8Dsd5Gf/9XbkA8Gf//bza6APV2WoE2vOrXs3Mt",
	"MfdcN+3HSV4tshkXJuJ83zGyJ8d1cGLCJ7tiZi+tenO6ce9Y/FcWm902LGux5iRJ/k/mLVLewVztI+i9",
	"xsX1FuA3Itl+dBR8ChcstBcLziSLWDY+L+cZiZ7D6jEHHVHHFTtUmHQGhiQvGJdO8qiax/B9GpzYtKne",
	"1y9YuLRwTeof9YjrHvBb6luTyGoTIKqh3zRuK6w0yDgVQo1nDWYPiQ+Hj9anZFuctSEbewNc50qSg+oh",
	"cXpb/Jn2O3t7p1/BPqlZ0K7ReJ0VeqMzZ258732g89M6DHAxaqLVfX+3FZseVUk6NWM7YGgzS70JYiKK",
	"DK9eacFzBzxjKUVTxQdtJD48bjnR7z98KD6/uFb/f6X/P71Go/GD8OKv3/heZ/JtPlrLJQsbyiL7YKvY",
	"gLYhOW5R8/hm0vkJ4UIabGgUBKMgw/UVgw+fAbn1QK3huz+Fwb0V58PFxZdbb11xQRi9LfPdQH8fzXeF",
	"jVux3mxLVYqz7HUSnLzfzd7sJB+URJfUasaNInnhq/Hxsiqhp1Vefz+53U5p/7soXx+aZ0wWvwIFjiXs",
	"WzSV4wW85dlgGes/35hCGv2grvScvZ6dIwGyLLyxKSaLqam46MenzEh1U8+UY1ribGiublFRBWnrHT5F",
	"+VZsUYDQ8VGusMTc4qG3pkhXpsWmHG+7GrsDuSj9kobbMm5NXSUBt15izlgGmKpHvAV4cVWAVxVF3c9c",
	"FBG1tvIv7qv16YqUUXhV5nMjNP0UT3N/Pfn5TTn43WxfLZuuJLZFrC0/XW4dmYpEl8Y1QR1c+9daLWxI",
	"0zwBU79G/oD97FzEKLUu8ha7eXf7viRZhuaAyIIyDvGd6oevYWds6hbP6EuQKfNA9C4lUaqTWCGhKNdP",
	"KRtp6zrdCnS3ILNwK80vNtm5FgjrwuyK+XTsxBS278d8FJZP7xmL9KuJuiiqgV6LlinQ+F9O0f5XFL/e",
	"jKL1bPMywfshwlTEvkzwTE871Jnx8pdTJRf6aSxhjM4SRJlUnh5iXP8jGYK8kCtkFj9CtoRXjXWEydbq",
	"esvOdBlrDwb1bvtiwmin1nUoTqkeGkLWl4UmKSzP75WKW588Np1rmkBpkxIcoQpbiDTeHCJCU9UpqrKV",
	"5XXgrNVV8+HDVlloF2ObaSJA/rvLtK4hiUpO5GqqJjPr+wdgDvy0VHzw2fQmaYdNX27gTKUsFJTN408z",
	"uDL+R49FUiJQ1fCAcryq2AKBHYMK4DnRyVgxQjEUQGNCF4hRZNoXlOxLQhdijH5hHMUgMckEEgCoCiLG",
	"LBLjCsOTRUliEBPFY5PqLaHzlqpPbHhtCj+EJsz6WhJH0qF/IMqiYFy6NLUhnlfqygOBpuYJ5cmqDWId",
	"7axHXHedtCnwKxKBEqZTRzh0X2AEdpdu33Ja4CgFdDw+6r1guVyOsb49ZnwxsWPF5MXZ46evpk/D4/HR",
	"OJV5psUaeC5eJ/bNdpKTyUQs8WIBXKFSPzJR6CEyqxeoIQxGwRVwk2oPvh8fjY8M5wLFBQlOgof6kgl1",
	"ae6ajJeQZeElZUs6+bi8FOOPwjiwC6NclKhpDXwWByfBryDfQZY9V48/W16KZ4KZojwTtNBTHh8dVSQC",
	"aqS5adSZVNM3TYEbitqnIA3t+02hhQ6FoktYCUQoevbuOZqakIQSZS1PZZ5jvjKQt55PGEfP3s2Q2w7o",
	"mWQUSLwQTe28mnSSAs5k+sc6LP1mHzkgbpy6bw9+KtYlAhlwVx2EGAhRlEJ06SzTPBxcXI90t3R/cb8B",
	"jtev7oYBURjPCL2ckFhWVRsFEx68nzMhTSeDrKtFtUn5B4tXN4Z3T6/EdVvFq/3e9Z1R/kzHweUKmd5l",
	"JEpdIpKUWbZqGRkdjvbZi/cX1xcuhdSKETa+Ao4iVlKJlkSmxrewhXYPRH2vFLpGmyISN8WGlqwKKL2R",
	"NzcMefMET5SHOFnYKOg60bLFelXA9JAi5g3M+oTNoHgddvtYrSZG3XCq8nzrWKpFW55gGzC1KCuwXC8I",
	"51geSAB6TdG3zP79BuNhkmiuRzbchDA6t2VTyNRN2c6OvaTCgDE0J/r2/HT2nUNBRTBDOtO3PsFuoHKY",
	"jp0czIFoOpDpubakPRAlO5X6m8ioEKe2LrRjQaa2HLnGaLZyEG/QHYyCBuEtOnTiPFsQo1XpckCCDPQQ",
	"3LK4raut35piY/SqzDJk60BRDpgKo/iiqpReb0MBYogHyKtNjqYWwjRu1bl2SW17s2nc0LVF861cCUPs",
	"wzoT3oL/2ybwzUqhJpOWRp/9r0lEarx2e4ddQlWewTaUso7BQSnV6RT4c1LKVG0Y8VOSxEGWnCJciydJ",
	"TPTE7oqE40P6SOk4J5tFT7l5dcxmE0lfS1NWeFCadvsg7pU3b3xDKm1+QrnZRgX23Xq/JGLEup0B3gl1",
	"cLcOCcYMBH0gEXwiQo4QkXWSyvpSY6R24DYmhkwIS3GKuYKNio4wVUN065BkKGI0IYuSQ/2eB8I0bhre",
	"WKCyQBhRWOqbY3Smp7RpsVbI0h7tYOATYx9XmrMrqi4YLwtOzBFKu3BifSTR4fmxXVx1J1Z/oPnDw6cv",
	"8YJEesu5M7tadXRT2miY7m4Cb3sd1OudOCjxBzs17pVW0pDtR+2WcsrXc83Xq5PaueQ2k8rtuFIelg/v",
	"bHt/CHd0uy16TabeXr0Kck0+V7+u14Wo2mccnjetqO4RkAO1oM0jk85RidejXpKLc7xCLEG2Nh/pEpf6",
	"HEdbquU7mq9VzN86EvGLi34+9ypddH2Phm0b0Nr1QB7IBmrvPG82tUTm8Mht3tyqPfK9+RB9Bh6yDtai",
	"+aCub/oA3rVkzQNMnYpFVYXVNrh0qrEauA5cWdsvfT3rn+C68eBUHxpvqDGiV1WZIAFyhGRKhI2J6IPu",
	"3Mx8ZVVa2XltyZaYSqEWqO2nTIHU4XllCW04RT8xB4RtQvzZuxkyR22Yvfl4ACe2nK1zfqcWzToT313g",
	"RccsPDw69h1sUpMD/Urkb/rAVedkXvdEXp+CtI9Oeif46qM/ZPiYsUsCvkSUFAijSN/WOiFGD3Tu97SU",
	"aaVljfV7giV+gHSWmVDPgTP6ADlEqCG4IX7DLWsm/RnPo++PH/6EzrFMf578hH6TsnhNs9VPaApRyeEn",
	"NMU5TImEn1/gTy3s944qXbfro0ifX3fsHpM77I7YrIw5WddzEO4mYziJcJbNcXS5u1V8XI28eevoo5k5",
	"TkdI473Rih2+VSrt8fTNLwpf0gj0d5VkmGca0VhD37Un+m7WtaVMGSd/NCVPFfliNF810uKX1xi+7O1T",
	"jaAaw0o+7b4LEF5gQoXRTBZ5FnNXOCuHTFN1zuIXAPXUPS5RudsdSayPa/S9vzpjc4f3PdGVLBDbIxad",
	"m3u9/L/d2XcCRBkvs0divKVqEJ6z0lCiOUN06PXGEA2/dmeNHWVEbdTcs1dxoril2fJ1sHQ72v1xBpib",
	"c2E3KXXNtgZoe4BNdWBY1Oii7bT5tnr8J/QSfwpPF/Dz0S4qvdKN2uHaRZ9bRd5S21UD2za7y6q/76Bb",
	"zG476J1EuHp9mJ79Zn3akw5SePaZldVdNmjr0aa+5yXKDpHIdu/lrVDobiORm+MB1vNx4oLeCGOFbFQT",
	"ZZhKI3u8vkOustg5V1wWt5UrHjh/4X7HbjgsiJDAIfbmh00ssV2hJ5CtRVUG4dHRwxsDvX1++QCXlQXK",
	"9UHRROQKlvpgbA3Mj7cHzFu1O9Q6Z0GugFZp8VYE0qOoymLLLHq5MZVXFjtYlLK4BYvSP2DgDiyKp7N/",
	"H4tSEWrAomjyeCyKQ5StLUpZ3JpFGTo44H5alLLYzaK0Cvb6VOpYlC0KUGYHLDzxHZ18N2TYwkpoUCGu",
	"DvVtxa86hKmPzfU92pBHtg6drT9I8HFZBf5LAXwSNz2h6ynVaSA9EM0G2lTvVWZQGyYHb9vXH/crLJ21",
	"IuyU99nYKEU41l0puoeELqxVY9z8+GvT9dRqYNEbvZQJoN3tvOkEHaN3RLsiNNbhQv3RIfuVEf0Cm/Oz",
	"jTBENDlEnVGMGRLMYbVu2aHmLFN+YD45sZm1nPbQA7KWpwn1HiadDc6QRYLyHE8rwth6l5bDqGPjKRZo",
	"DkDrJLOiH4WlYiC+oXB7TQGwgUQzY901ZonufjqmT3fFW60PUYVbVCOsb4g9NF+s7cK9h2zSYgJblKCI",
	"v64yQUk8DIzegrb26Oj1FHyZ4AOSymkIvlc02atB4tS2HSszbH+il2UmSZjgSDLejzN6uiWqDHZDpu12",
	"72536gEJdsf79fVUq4CzOnfPVqLR52G1WdHCVO7oS3kppM5XtvKdjFeBT4SbjwV2JLKzS21Re6K7oben",
	"ufl+4G0Q3ul8vp/UN33ktcHtOdz6OsJNeakesI1druq3XLNsS7Aqy7yJyM0udyjtWO9qd0svut/2vB5t",
	"+Xjzjc0thnS/ALtjMoY359vdSH7l2rvDNbIm6haq+cpjIkf2mlvV1nWuv21q/b4baXlusYtD6NY2uW5n",
	"XktgQb68D3mHMwccoJo80dH4aHwUxnC18WSEarjnCICeFNrF1d++tX3h/ebmqxoLDh7NaxRp/zcAAP//",
	"CdGrMwt5AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
