name: Build
on:
  pull_request:
    branches: [main]
    paths:
      - '**'
      - '!docs/**'
      - '!examples/**'
      - '!*.md'
  push:
    branches: [main]
    paths:
      - '**'
      - '!docs/**'
      - '!examples/**'
      - '!*.md'
jobs:
  test:
    uses: nhost/hasura-auth/.github/workflows/test.yml@main
  coverage:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download coverage results
        uses: actions/download-artifact@v1
        with:
          name: coverage
      - name: Publish to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/clover.xml
  publish:
    needs: test
    if: github.event_name == 'push'
    uses: nhost/hasura-auth/.github/workflows/publish.yml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_STAGING_ACCOUNT_ID: ${{ secrets.AWS_STAGING_ACCOUNT_ID }}
      AWS_PRODUCTION_ACCOUNT_ID: ${{ secrets.AWS_PRODUCTION_ACCOUNT_ID }}
