name: Trigger auto deployment for hasura-auth

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ optinizations ]
    paths:
    - 'Dockerfile/**'
    - '.github/workflows/hasura-auth-AutoDeployTrigger-525010a8-b034-44b6-af35-36a1a36b467c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: writingmatebackend.azurecr.io
          username: ${{ secrets.HASURAAUTH_REGISTRY_USERNAME }}
          password: ${{ secrets.HASURAAUTH_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: writingmatebackend.azurecr.io/hasura-auth:${{ github.sha }}
          file: Dockerfile/Dockerfile
          context: Dockerfile/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HASURAAUTH_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n hasura-auth -g production --server writingmatebackend.azurecr.io --username  ${{ secrets.HASURAAUTH_REGISTRY_USERNAME }} --password ${{ secrets.HASURAAUTH_REGISTRY_PASSWORD }}
            az containerapp update -n hasura-auth -g production --image writingmatebackend.azurecr.io/hasura-auth:${{ github.sha }}
