name: Test
on:
  workflow_call:
  pull_request:
    branches: [main]
    paths:
      - '**'
      - '!docs/**'
      - '!examples/**'
      - '!*.md'

env:
  POSTGRES_PASSWORD: postgrespassword
  HASURA_GRAPHQL_ADMIN_SECRET: test_secret_key
  HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key":"never_use_this_secret_key_in_production_this_is_only_for_CI_testing_098hu32r4389ufb4n38994321","issuer":"hasura-auth"}'
  HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@localhost:5432/postgres
  HASURA_GRAPHQL_GRAPHQL_URL: http://localhost:8080/v1/graphql
  AUTH_SERVER_URL: http://localhost:4000
  AUTH_CLIENT_URL: http://localhost:3000
  AUTH_SMTP_HOST: localhost
  AUTH_SMTP_PORT: 1025
  AUTH_SMTP_USER: user
  AUTH_SMTP_PASS: password
  AUTH_SMTP_SENDER: hasura-auth@example.com
  AUTH_SMTP_SECURE: false
  AUTH_EMAIL_PASSWORDLESS_ENABLED: true
  AUTH_LOG_LEVEL: info

jobs:
  test:
    name: Service tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node and dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run tests
        shell: bash
        run: make test
