---
on:
  workflow_call:
    inputs:
      NAME:
        type: string
        required: true
      GIT_REF:
        type: string
        required: false

jobs:
  tests:
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: write


    runs-on: ubuntu-22.04
    timeout-minutes: 180

    steps:
    - name: "Check out repository"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ inputs.GIT_REF }}

    - uses: actions/cache@v4
      with:
        path: |
          /nix/store
          /nix/var/nix/db
          ~/.cache/nix
        key: ${{ runner.os }}-${{ runner.arch }}-nix-check-${{ hashFiles('**/*.nix') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-nix-check-

    - uses: cachix/install-nix-action@v30
      with:
        install_url: "https://releases.nixos.org/nix/nix-2.22.3/install"
        install_options: "--no-daemon"
        extra_nix_config: |
          experimental-features = nix-command flakes
          sandbox = false
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          substituters = https://cache.nixos.org/?priority=40
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - name: "Verify if we need to build"
      id: verify-build
      run: |
        export drvPath=$(make check-dry-run-go)
        echo "drvPath - $drvPath"
        nix store verify $drvPath \
          && export BUILD_NEEDED=no \
          || export BUILD_NEEDED=yes

        if [ "$BUILD_NEEDED" != "yes" ]; then
          export check_dry_run_output=$(make check-dry-run-node)
          export drvPath=$(echo "$check_dry_run_output" | grep -oE '"out":.*"' | awk -F\" '{ print $4 }')
          nix store verify $drvPath \
            && export BUILD_NEEDED=no \
            || export BUILD_NEEDED=yes
        fi

        echo BUILD_NEEDED=$BUILD_NEEDED >> $GITHUB_OUTPUT
        echo DERIVATION_PATH=$drvPath >> $GITHUB_OUTPUT

    - name: "Start containters for integration tests"
      run: |
        make build-docker-image
        nix develop -c make dev-env-up
      if: ${{ steps.verify-build.outputs.BUILD_NEEDED == 'yes' }}

    - name: "Run checks"
      run: make check
      if: ${{ steps.verify-build.outputs.BUILD_NEEDED == 'yes' }}
